version: "3.4"
services:

  server:
    image: tengelisconsulting/docker-http-server:latest
    network_mode: "host"
    environment:
      - PORT
      - HOOK_KEY
      - WORK_PORT
      - LOCAL_HOOK_PORT
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
