#!/bin/bash

docker build -t tengelisconsulting/docker-http-server:latest ./server
docker push tengelisconsulting/docker-http-server:latest
docker build -t tengelisconsulting/docker-http-worker:latest ./worker
docker push tengelisconsulting/docker-http-worker:latest

docker build -t tengelisconsulting/docker-http .
